### ISSUE TITLE
Why is this extention banned from Chrome Webstore

### ISSUE THREAD

**Issue by Quiet-Wildcard** [nickscript0/chrome-bookmarks-table#1]
Since a few days i get an error that Bookmarks Table is bannend . 
Chrome disabled the extention and get "This extension violates the Chrome Web Store policy".

Can someone tell me what is going on?

**Comment by nickscript0** [comment]
It appears to have been taken down due to missing some new extension requirements the Chrome Web Store recently introduced (Single Purpose statement, Permission justification statement, ...). 

I've now fixed this and re-submitted. It says it is under review and should be published within a couple weeks.

**Comment by nickscript0** [comment]
The extension is live again.
